#!/usr/bin/env bash
set -euo pipefail

host="${RUBIS_CASSANDRA_HOST:-cassandra-rubis}"
keyspace="${RUBIS_CASSANDRA_KEYSPACE:-rubis}"

ruby - <<RUBY
require 'cassandra'

host = '${host}'
keyspace = '${keyspace}'

cluster = Cassandra.cluster(hosts: [host], port: 9042)
session = cluster.connect
session.execute("DROP KEYSPACE IF EXISTS #{keyspace}")
session.execute(
  "CREATE KEYSPACE #{keyspace} " \
  "WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}"
)
cluster.close
puts "Reset Cassandra keyspace #{keyspace} on #{host}"
RUBY

